//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisEntCat
    {
        public int Id { get; set; }
        public int HisCategoryId { get; set; }
        public int HisEntityId { get; set; }
    
        public virtual HisCategory HisCategory { get; set; }
        public virtual HisEntity HisEntity { get; set; }
    }
}
