//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HisNotification()
        {
            this.HisNotificationRecipients = new HashSet<HisNotificationRecipient>();
        }
    
        public int Id { get; set; }
        public string RecType { get; set; }
        public string Recipient { get; set; }
        public string Message { get; set; }
        public System.DateTime DtSending { get; set; }
        public Nullable<int> RefId { get; set; }
        public string RefTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HisNotificationRecipient> HisNotificationRecipients { get; set; }
    }
}
