//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HisOrder()
        {
            this.HisResults = new HashSet<HisResult>();
            this.HisOrderRemarks = new HashSet<HisOrderRemarks>();
        }
    
        public int Id { get; set; }
        public string SpecimenId { get; set; }
        public int HisOrderTypeId { get; set; }
        public int HisProfileId { get; set; }
        public int HisPhysicianId { get; set; }
        public int HisInstrumentId { get; set; }
        public Nullable<System.DateTime> dtRequest { get; set; }
        public Nullable<System.DateTime> dtProcessed { get; set; }
        public Nullable<System.DateTime> dtReleased { get; set; }
    
        public virtual HisOrderType HisOrderType { get; set; }
        public virtual HisProfile HisProfile { get; set; }
        public virtual HisPhysician HisPhysician { get; set; }
        public virtual HisInstrument HisInstrument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HisResult> HisResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HisOrderRemarks> HisOrderRemarks { get; set; }
    }
}
