//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisResult
    {
        public int Id { get; set; }
        public int HisOrderId { get; set; }
        public int HisResultFieldId { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public string Remarks { get; set; }
    
        public virtual HisOrder HisOrder { get; set; }
        public virtual HisResultField HisResultField { get; set; }
    }
}
