//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisReqCat
    {
        public int Id { get; set; }
        public int HisReqCategoryId { get; set; }
        public int HisRequestId { get; set; }
    
        public virtual HisReqCategory HisReqCategory { get; set; }
        public virtual HisRequest HisRequest { get; set; }
    }
}
