//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.HIS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisResultField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HisResultField()
        {
            this.SeqNo = 100;
            this.HisResults = new HashSet<HisResult>();
            this.HisInsResultRanges = new HashSet<HisResultRange>();
        }
    
        public int Id { get; set; }
        public int HisOrderTypeId { get; set; }
        public Nullable<int> AddForType { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public int SeqNo { get; set; }
        public string minValue { get; set; }
        public string maxValue { get; set; }
        public string Uom { get; set; }
    
        public virtual HisOrderType HisOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HisResult> HisResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HisResultRange> HisInsResultRanges { get; set; }
    }
}
